version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - FEATURE_STORE_URI=postgres://user:pass@db:5432/features
    depends_on:
      - db
      - redis

  ingest:
    build: ./ingest
    environment:
      - QUEUE_URI=redis://redis:6379/0
    depends_on:
      - redis
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: features
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
